### ISSUE TITLE
PageResponse.java Issue for Me.

### ISSUE THREAD

**Issue by SocialRaceMedia** [ticketmaster-api/sdk-java#13]
Hello:

I am using the Java SDK on a NetBeans 8.1 platform with java sdk of 1.8_102
All the most recent Jackson libraries from the Maven Repo.  
jackson-databind-2.8.2.jar

When I load the PagedResponse.java file I am receiving this message :
<-----------------------------------------------
reference to readValue is ambiguous
  both method <T#1>readValue(String,TypeReference) in ObjectMapper and method <T#2>readValue(String,JavaType) in ObjectMapper match
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>readValue(String,TypeReference)
    T#2 extends Object declared in method <T#2>readValue(String,JavaType)
-------------------------------------------------->

on this line of code

this.page = mapper.readValue(httpResponse.body().string(), javaType);

from this 

  protected void readContent() {
        try {
            this.page = mapper.readValue(httpResponse.body().string(), javaType);         *****\* Error Message on this Line

```
    } catch (IOException ioe) {
        throw new RuntimeException(ioe);
    }
    this.content = page.getEmbedded();
}
```

**Comment by ledor473** [comment]
Thanks for reporting! 
We'll look into it as soon as possible.

Could you provide the pom.xml you are using (you can remove any non-public dependancies).

**Comment by ledor473** [comment]
@SocialRaceMedia  the SDK depends on the version 2.7.0 of `jackson-databind`
https://github.com/ticketmaster-api/sdk-java/blob/master/discovery/build.gradle#L8

That being said, I've updated (locally) the version of `jackson-core`, `jackson-databind`, `jackson-datatype-joda` to 2.8.2 but I couldnt reproduce your issue as there was no compilation error.

**Comment by SocialRaceMedia** [comment]
Thank You Louis for all the help.  You definitely got me going in the correct direction.  Look forward to working more in the future
