### ISSUE TITLE
Search Multiple Keywords?

### ISSUE THREAD

**Issue by MalcolmMcFly** [ticketmaster-api/sdk-java#24]
Is there a way to search for events using multiple keywords? For example, I'd like to get back a list of sports and music related events.

**Comment by ledor473** [comment]
You should use the Event Search with the classificationId or classificationName for that instead of searching by keyword.

**Comment by MalcolmMcFly** [comment]
@ledor473 can we search multiple classifcationIds or multiple classificationNames, or are we limited to just 1 there as well?

**Comment by ledor473** [comment]
@MalcolmMcFly Yes you can pass multiple values to both filter (e.g. ?classificationName=Rock,Pop)
